#!/bin/bash

# Change directory to the PRODUCT_DIR (e.g. out/Release).
export LD_LIBRARY_PATH=`pwd`

cd build
gclient config http://webrtc.googlecode.com/svn/trunk
gclient runhooks --force
gclient sync --force
cd ..
ninja -C build/trunk/out/Debug
#cd ../../
# move jar and shared native lib to libs dir
#mv build/trunk/out/Release/libjingle_peerconnection.jar libs/
#mv build/trunk/out/Release/libjingle_peerconnection_so.so libs/
# remove old build files
#rm -rf build/*
